export interface SubDomain {
  name: string
  description: string
}

export interface LearningDomain {
  id: number
  num: string
  name: string
  category: string
  color: string
  description: string
  purpose: string
  subDomains: SubDomain[]
  frameworks: string[]
  tools: string[]
  aiAdvisor: string
  outputs: string[]
  difficulty: 'Foundation' | 'Intermediate' | 'Advanced'
  track: string
}

export const categories = [
  'All',
  'Strategy',
  'Architecture',
  'Data & AI',
  'Governance & Risk',
  'Intelligence',
  'Operations & People',
  'Advanced Capabilities',
]

export const learningDomains: LearningDomain[] = [
  {
    id: 1,
    num: '01',
    name: 'Strategy Intelligence',
    category: 'Strategy',
    color: 'blue',
    difficulty: 'Intermediate',
    track: 'Strategy & Planning',
    description: 'Generate, evaluate, and refine enterprise strategy by combining internal goals with external signals and AI-powered analysis.',
    purpose: 'Enable AI-augmented strategic planning that connects vision to actionable initiatives with full traceability.',
    subDomains: [
      { name: 'Strategic Planning', description: 'Define vision, OKRs, and multi-year strategic roadmaps aligned to enterprise goals.' },
      { name: 'SWOT Analysis', description: 'AI-generated SWOT matrices connecting strengths/weaknesses to opportunities/threats.' },
      { name: 'PESTLE Analysis', description: 'Macro-environmental scan across Political, Economic, Social, Technological, Legal, and Environmental factors.' },
      { name: 'Competitive Analysis', description: "Porter's Five Forces evaluation of competitive dynamics, market share, and differentiation." },
      { name: 'Industry Intelligence', description: 'Real-time sector benchmarks, market trends, and disruption signal monitoring.' },
      { name: 'Strategic Initiative Generation', description: 'AI-generated initiative portfolios scored by impact, feasibility, and strategic urgency.' },
    ],
    frameworks: ["Porter's Five Forces", 'SWOT', 'PESTLE', 'OKR', 'Balanced Scorecard', 'Blue Ocean Strategy'],
    tools: ['LangGraph', 'GraphRAG', 'Neo4j', 'Semantic Kernel'],
    aiAdvisor: 'Chief Strategy Officer Agent',
    outputs: ['Strategic Themes', 'Strategic Roadmaps', 'OKR Frameworks', 'Investment Priority Lists', 'Transformation Programs'],

  },
  {
    id: 2,
    num: '02',
    name: 'External Forces Intelligence',
    category: 'Strategy',
    color: 'sky',
    difficulty: 'Intermediate',
    track: 'Strategy & Planning',
    description: 'Continuously monitor 10 categories of external forces that affect enterprise strategy — the essential starting point for all strategic reasoning.',
    purpose: 'Move beyond internal goal-setting to a full strategic intelligence model that starts with the outside world.',
    subDomains: [
      { name: 'Macroeconomic Forces', description: 'GDP, inflation, interest rates, and employment trends from Federal Reserve, IMF, World Bank, and OECD.' },
      { name: 'Industry Forces', description: "Porter's Five Forces competitive structure: rivalry, new entrants, supplier/customer power, substitutes." },
      { name: 'Technology Forces', description: 'Technology radar tracking AI (Agentic AI, AGI), Cloud (multi-cloud, sovereign), Data (Mesh, Knowledge Graphs), and Security (Zero Trust, Post-Quantum).' },
      { name: 'Regulatory Forces', description: 'Privacy (GDPR, CCPA), AI regulation (EU AI Act, NIST AI RMF, ISO 42001), Financial (SOX, Basel), and Industry (PCI DSS, HIPAA).' },
      { name: 'Geopolitical Forces', description: 'Trade policies, tariffs, sanctions, regional conflicts, and supply chain disruptions affecting operations.' },
      { name: 'Market Forces', description: 'Customer behavior shifts, demographic changes, digital adoption curves, and consumer sentiment.' },
      { name: 'Workforce Forces', description: 'AI skills shortage, remote work evolution, labor availability, and workforce demographic trends.' },
      { name: 'Ecosystem Forces', description: 'Vendor lock-in risks, strategic partner viability, SaaS concentration, and open-source community health.' },
      { name: 'Sustainability & ESG', description: 'Carbon reduction obligations, energy consumption, ESG reporting mandates (SEC, EU CSRD), and sustainable supply chain requirements.' },
      { name: 'Disruption Intelligence', description: 'AI-native competitors, new business model entrants, industry convergence signals, and platform disruption patterns.' },
    ],
    frameworks: ['PESTLE', "Porter's Five Forces", 'STEEP', 'Scenario Planning', 'Horizon Scanning'],
    tools: ['Gartner Hype Cycle', 'Forrester Wave', 'arXiv feeds', 'News Intelligence APIs'],
    aiAdvisor: 'Chief Strategy Officer Agent',
    outputs: ['Opportunity Analysis', 'Threat Analysis', 'Strategic Impact Assessment', 'External Forces Dashboard', 'Force Scoring Matrix'],
  },
  {
    id: 3,
    num: '03',
    name: 'Business Architecture',
    category: 'Architecture',
    color: 'violet',
    difficulty: 'Intermediate',
    track: 'Enterprise Architecture',
    description: 'Map, analyze, and evolve business capabilities, value streams, and processes to bridge strategy and execution.',
    purpose: 'Create a structured representation of how the business operates so strategy can be connected to capabilities and transformation programs.',
    subDomains: [
      { name: 'Capability Mapping', description: 'Define and decompose business capabilities at L1/L2/L3, assess maturity, and create heat maps showing investment vs. performance gaps.' },
      { name: 'Value Streams', description: 'Model end-to-end value creation flows from trigger to outcome, identifying waste and handoff inefficiencies.' },
      { name: 'Process Models', description: 'Document and optimize business processes using BPMN 2.0 notation and APQC Process Classification Framework.' },
      { name: 'Business Information Models', description: 'Define business entities, information flows, conceptual data models, and the business glossary.' },
    ],
    frameworks: ['BIZBOK', 'APQC PCF', 'BPMN 2.0', 'Value Stream Mapping', 'Lean Six Sigma'],
    tools: ['ArchiMate', 'Sparx EA', 'Signavio', 'LeanIX'],
    aiAdvisor: 'Chief Architect Advisor',
    outputs: ['Capability Heat Maps', 'Capability Roadmaps', 'Value Stream Diagrams', 'Business Transformation Models', 'Business Glossary'],
  },
  {
    id: 4,
    num: '04',
    name: 'Operating Model',
    category: 'Architecture',
    color: 'purple',
    difficulty: 'Intermediate',
    track: 'Enterprise Architecture',
    description: 'Assess current operating models and design future-state models across people, process, technology, governance, and metrics.',
    purpose: 'Ensure transformation programs address not just technology but the full operating model change required for sustainable outcomes.',
    subDomains: [
      { name: 'Current State Assessment', description: 'Baseline the as-is operating model across org structure, processes, technology, governance, and performance metrics.' },
      { name: 'Target Operating Model', description: 'Design the future-state TOM blueprint with transition plan, workforce impact, and technology enablement requirements.' },
      { name: 'Product Operating Models', description: 'Stream-aligned product team structures, OKR alignment, product governance, and discovery/delivery flows.' },
      { name: 'Platform Operating Models', description: 'Internal platform team design, developer experience, self-serve enablement, SLA frameworks, and chargeback models.' },
      { name: 'AI Operating Models', description: 'AI Center of Excellence design, human-in-the-loop governance, model lifecycle management, and AI risk oversight.' },
    ],
    frameworks: ['McKinsey 7S', 'Team Topologies', 'ITIL', 'SAFe', 'Spotify Model'],
    tools: ['Miro', 'Lucidchart', 'Orgvue', 'ServiceNow'],
    aiAdvisor: 'Transformation Office Advisor',
    outputs: ['TOM Blueprints', 'Workforce Transformation Plans', 'Organizational Design Models', 'AI Operating Model Blueprint'],
  },
  {
    id: 5,
    num: '05',
    name: 'Enterprise Architecture',
    category: 'Architecture',
    color: 'indigo',
    difficulty: 'Advanced',
    track: 'Enterprise Architecture',
    description: 'Define current and future-state enterprise architecture, govern technology decisions, and produce transformation roadmaps.',
    purpose: 'Provide the authoritative blueprint for how technology, data, applications, and infrastructure support business capabilities and strategy.',
    subDomains: [
      { name: 'Current State Architecture', description: 'Document the as-is application portfolio, integration topology, infrastructure, technical debt, and architecture maturity.' },
      { name: 'Future State Architecture', description: 'Design target architecture for applications, cloud platforms, integration patterns, data, and security.' },
      { name: 'Architecture Governance', description: 'Architecture Review Board workflows, technology standards catalog, compliance scoring, and waiver management.' },
      { name: 'Technology Rationalization', description: 'Application redundancy analysis, cost-per-capability mapping, retirement roadmap, and vendor contract optimization.' },
      { name: 'Architecture Decision Records', description: 'Capture decisions with context, alternatives, rationale, and outcomes for full architectural memory and traceability.' },
    ],
    frameworks: ['TOGAF ADM', 'ArchiMate 3.1', 'Zachman Framework', 'C4 Model', 'SABSA'],
    tools: ['LeanIX', 'Sparx EA', 'Ardoq', 'Structurizr', 'Neo4j'],
    aiAdvisor: 'Chief Architect Advisor',
    outputs: ['Reference Architectures', 'Transformation Roadmaps', 'Architecture Decision Records', 'Technology Standards Catalog', 'Compliance Assessment Reports'],
  },
  {
    id: 6,
    num: '06',
    name: 'Data & AI Intelligence',
    category: 'Data & AI',
    color: 'cyan',
    difficulty: 'Advanced',
    track: 'Data & AI Architecture',
    description: 'Define data strategy, design AI architectures, build knowledge graphs, and govern data and AI programs across the enterprise.',
    purpose: 'Make data and AI first-class enterprise capabilities — governed, trusted, and strategically aligned.',
    subDomains: [
      { name: 'Data Strategy', description: 'Enterprise data vision, maturity assessment, platform direction, and multi-year data investment roadmap.' },
      { name: 'Data Mesh', description: 'Domain-oriented data ownership, data as a product, self-serve data platforms, and federated computational governance.' },
      { name: 'Data Products', description: 'Discoverable, addressable, trustworthy, self-describing, and interoperable data products with quality SLAs.' },
      { name: 'Data Governance', description: 'Data ownership, stewardship, quality rules, lineage tracking, catalog management, and regulatory compliance (GDPR, CCPA, HIPAA).' },
      { name: 'AI Strategy', description: 'AI vision, use case prioritization, build/buy/partner decisions, capability roadmap, and AI investment planning.' },
      { name: 'Agentic AI', description: 'Autonomous agent design with LangGraph, tool/memory architecture, human-in-the-loop controls, and observability.' },
      { name: 'Multi-Agent Systems', description: 'Orchestrator-worker patterns, peer-to-peer agent collaboration, role specialization, and inter-agent communication protocols.' },
      { name: 'Knowledge Graphs', description: 'Enterprise knowledge representation using Neo4j, GraphRAG, RDF/OWL, and vector search for AI reasoning.' },
      { name: 'AI Governance', description: 'AI risk classification (EU AI Act tiers), bias assessment, explainability, human oversight, and AI incident response.' },
    ],
    frameworks: ['Data Mesh', 'DAMA-DMBOK', 'DCAM', 'EU AI Act', 'NIST AI RMF', 'ISO 42001'],
    tools: ['Databricks', 'Snowflake', 'BigQuery', 'Neo4j', 'Pinecone', 'Weaviate', 'LangGraph', 'CrewAI', 'Semantic Kernel', 'MCP'],
    aiAdvisor: 'Chief Data Officer Advisor · AI Governance Advisor',
    outputs: ['Enterprise AI Blueprint', 'Data Operating Model', 'Agent Architectures', 'Enterprise Knowledge Graph', 'AI Risk Register'],
  },
  {
    id: 7,
    num: '07',
    name: 'Governance, Risk & Compliance',
    category: 'Governance & Risk',
    color: 'red',
    difficulty: 'Intermediate',
    track: 'Governance & Risk',
    description: 'Establish enterprise governance frameworks, risk management practices, and compliance programs across all domains.',
    purpose: 'Protect the enterprise from strategic, technology, cyber, and AI risks while maintaining compliance with regulatory obligations.',
    subDomains: [
      { name: 'Portfolio Governance', description: 'Stage-gate review processes, portfolio health monitoring, initiative dependency management, and benefits accountability.' },
      { name: 'Architecture Governance', description: 'Architecture Review Board, technology standards enforcement, compliance scoring, and exception management.' },
      { name: 'Data Governance', description: 'Data ownership policies, classification/sensitivity labeling, privacy management, and regulatory data compliance.' },
      { name: 'AI Governance', description: 'AI risk classification, bias/fairness assessments, explainability documentation, human override mechanisms, and AI audit trails.' },
      { name: 'Risk Management', description: 'Strategic, technology, cyber, and AI risk identification, assessment, mitigation planning, and monitoring.' },
      { name: 'Compliance', description: 'SOX, PCI DSS, GDPR, CCPA, HIPAA, ISO 27001, ISO 42001, Basel, and Dodd-Frank compliance mapping and evidence management.' },
    ],
    frameworks: ['COBIT 2019', 'NIST CSF', 'ISO 27001', 'ISO 42001', 'COSO ERM', 'TOGAF Governance'],
    tools: ['ServiceNow GRC', 'RSA Archer', 'OneTrust', 'Vanta', 'Drata'],
    aiAdvisor: 'AI Governance Advisor',
    outputs: ['Governance Frameworks', 'Risk Registers', 'Compliance Maps', 'Audit Evidence Packages', 'AI Ethics Policy'],
  },
  {
    id: 8,
    num: '08',
    name: 'Investment & Value Realization',
    category: 'Strategy',
    color: 'emerald',
    difficulty: 'Intermediate',
    track: 'Finance & Investment',
    description: 'Build compelling business cases, optimize investment portfolios, and track whether transformation programs deliver their promised value.',
    purpose: 'Ensure every transformation dollar is justified, optimized, and measured — connecting investment to measurable business outcomes.',
    subDomains: [
      { name: 'Business Case', description: 'AI-generated business cases with executive summary, financial models (ROI, NPV, IRR), risk assessment, and implementation approach.' },
      { name: 'Investment Planning', description: 'Run/grow/transform budget allocation, multi-year investment roadmap, and scenario-based investment modeling.' },
      { name: 'Portfolio Optimization', description: 'Multi-criteria initiative scoring, constraint-based portfolio optimization, dependency sequencing, and trade-off analysis.' },
      { name: 'Benefits Realization', description: 'Benefit ownership assignment, KPI baseline establishment, periodic measurement, variance analysis, and course-correction.' },
    ],
    frameworks: ['Business Case Standard', 'Managing Benefits (MSP)', 'Portfolio Management (MoP)', 'Earned Value Management'],
    tools: ['Planview', 'Clarity PPM', 'Excel/Python Financial Models', 'PowerBI'],
    aiAdvisor: 'CFO Advisor',
    outputs: ['Business Cases', 'Executive Financial Models', 'Investment Prioritization Matrix', 'Benefits Realization Reports', 'Portfolio Health Dashboards'],
  },
  {
    id: 9,
    num: '09',
    name: 'Enterprise Memory',
    category: 'Intelligence',
    color: 'amber',
    difficulty: 'Advanced',
    track: 'Intelligence & Knowledge',
    description: 'Capture, preserve, and make searchable all significant organizational knowledge — so the enterprise never forgets and learns from history.',
    purpose: 'Transform ephemeral organizational knowledge into a persistent, queryable intelligence asset that improves every future decision.',
    subDomains: [
      { name: 'Decisions', description: 'Every significant decision captured with context, alternatives, rationale, expected outcomes, and actual results.' },
      { name: 'Architecture Artifacts', description: 'Version-controlled repository of architecture documents, ADRs, diagrams, and reference patterns.' },
      { name: 'Lessons Learned', description: 'Post-mortem insights, transformation retrospectives, failure patterns, and success factors captured for future reuse.' },
      { name: 'Risk History', description: 'Historical risk events, mitigation strategies that worked or failed, residual risk assessments, and risk patterns by domain.' },
    ],
    frameworks: ['Knowledge Management (KM)', 'Enterprise Architecture Repository', 'TOGAF ADM Output Management'],
    tools: ['Neo4j', 'GraphRAG', 'Confluence', 'Vector Databases (Pinecone, Weaviate)'],
    aiAdvisor: 'Chief Architect Advisor',
    outputs: ['Enterprise Memory Graph', 'Decision Traceability Map', 'Architecture History Timeline', 'Organizational Learning Repository'],
  },
  {
    id: 10,
    num: '10',
    name: 'Decision Intelligence',
    category: 'Intelligence',
    color: 'orange',
    difficulty: 'Advanced',
    track: 'Intelligence & Knowledge',
    description: 'Provide AI-powered decision support that synthesizes enterprise context, memory, and external intelligence into actionable recommendations.',
    purpose: 'Augment executive decision-making with structured AI reasoning so decisions are faster, better-evidenced, and consistently high-quality.',
    subDomains: [
      { name: 'Strategy Recommendations', description: 'AI-driven strategic theme prioritization, initiative selection, market entry/exit, and capability investment guidance.' },
      { name: 'Architecture Recommendations', description: 'Technology selection, architecture pattern suggestions, cloud direction, and integration approach guidance.' },
      { name: 'Investment Recommendations', description: 'AI-scored investment rankings using strategic alignment, ROI, risk-adjustment, capability impact, and feasibility.' },
      { name: 'Risk Assessments', description: 'Automated risk scoring across probability, impact, velocity, detectability, and control effectiveness.' },
      { name: 'Scenario Simulations', description: 'Multi-variable what-if analysis using Monte Carlo modeling, sensitivity analysis, and best/base/worst case planning.' },
    ],
    frameworks: ['Decision Analysis (DA)', 'MCDA', 'Bayesian Decision Theory', 'Scenario Planning'],
    tools: ['LangGraph', 'GraphRAG', 'Python (scipy, numpy)', 'Claude / GPT / Gemini'],
    aiAdvisor: 'Executive Board Advisor',
    outputs: ['Decision Packages', 'Executive Briefings', 'Scenario Analysis Reports', 'Confidence-Scored Recommendations'],
  },
  {
    id: 11,
    num: '11',
    name: 'Enterprise Digital Twin',
    category: 'Advanced Capabilities',
    color: 'teal',
    difficulty: 'Advanced',
    track: 'Advanced Intelligence',
    description: 'Create a continuously updated living model of the enterprise enabling simulation, impact analysis, and what-if scenario planning.',
    purpose: 'Allow executives to simulate the impact of transformation decisions on capabilities, processes, technology, and workforce before committing resources.',
    subDomains: [
      { name: 'Capability Twin', description: 'Live model of all capabilities with maturity, investment, strategic importance, and gap scores — enabling what-if investment simulations.' },
      { name: 'Process Twin', description: 'Simulated process models for automation impact modeling, redesign scenario comparison, and bottleneck identification.' },
      { name: 'Technology Twin', description: 'Live technology estate model for migration impact analysis, application dependency mapping, and decommissioning blast-radius assessment.' },
      { name: 'Organization Twin', description: 'Org structure, role inventory, skills/competencies, and team topology for workforce transformation simulation.' },
    ],
    frameworks: ['Digital Twin Consortium Standards', 'ArchiMate', 'TOGAF', 'Team Topologies'],
    tools: ['Neo4j', 'Azure Digital Twins', 'Python Simulation', 'D3.js', 'LeanIX'],
    aiAdvisor: 'Chief Architect Advisor',
    outputs: ['Transformation Simulations', 'Risk Forecasts', 'Impact Analysis Reports', 'Change Readiness Assessments'],
  },
  {
    id: 12,
    num: '12',
    name: 'Learning Academy',
    category: 'Operations & People',
    color: 'lime',
    difficulty: 'Foundation',
    track: 'Learning & Development',
    description: 'Develop enterprise capabilities through structured learning paths, certifications, and industry playbooks across all EWP domains.',
    purpose: 'Build organizational competence alongside platform intelligence so the enterprise can actually apply the wisdom it generates.',
    subDomains: [
      { name: 'Business Strategy Track', description: 'Strategic planning, SWOT/PESTLE/Porter frameworks, OKR design, competitive intelligence, and strategy-to-execution alignment.' },
      { name: 'Business Architecture Track', description: 'Capability mapping, value streams, BPMN process modeling, BIZBOK and APQC frameworks, and operating model design.' },
      { name: 'Enterprise Architecture Track', description: 'TOGAF ADM, ArchiMate modeling, Zachman Framework, architecture governance, and technology rationalization.' },
      { name: 'Data Architecture Track', description: 'Data strategy, Data Mesh principles, data product design, data governance, and modern platform architecture.' },
      { name: 'AI Architecture Track', description: 'Enterprise AI strategy, LLM selection, agentic AI design, multi-agent systems, and AI governance (EU AI Act, NIST AI RMF).' },
      { name: 'Governance Track', description: 'GRC framework fundamentals (COBIT, NIST, ISO), enterprise risk management, compliance program design, and AI governance.' },
    ],
    frameworks: ['TOGAF', 'BIZBOK', 'DAMA-DMBOK', 'COBIT', 'NIST', 'EU AI Act'],
    tools: ['LMS Platforms', 'EWP Platform', 'Case Study Library', 'Assessment Engine'],
    aiAdvisor: 'All AI Advisors',
    outputs: ['Learning Paths', 'Certifications', 'Industry Playbooks', 'Competency Assessments', 'Executive Deep Dives'],
  },
  {
    id: 13,
    num: '13',
    name: 'Organizational Intelligence',
    category: 'Operations & People',
    color: 'pink',
    difficulty: 'Intermediate',
    track: 'People & Change',
    description: 'Analyze human factors — culture, politics, incentives, and stakeholder dynamics — that determine whether transformations succeed or fail.',
    purpose: 'Address the most common reason transformations fail: not technology, but people, politics, and change resistance.',
    subDomains: [
      { name: 'Stakeholder Analysis', description: 'Stakeholder identification, power/interest grid, stance assessment, engagement strategy, and communication plan design.' },
      { name: 'Organizational Network Analysis', description: 'Informal influence mapping, information flow analysis, silo detection, and change champion identification.' },
      { name: 'Change Management', description: 'ADKAR journey design, Kotter 8-step program, Bridges transition management, resistance handling, and sustainability planning.' },
      { name: 'Leadership Alignment', description: 'Executive vision alignment, decision rights clarity, resource commitment, and consistent leadership communication.' },
      { name: 'Decision Culture', description: 'Decision speed/quality assessment, RACI analysis, behavioral economics bias identification, and decision culture improvement.' },
    ],
    frameworks: ['ADKAR', "Kotter's 8-Step Model", 'Bridges Transition Model', 'McKinsey 7S', 'Prosci'],
    tools: ['ONA Tools', 'Stakeholder Mapping Tools', 'Survey Platforms', 'Change Tracking Dashboards'],
    aiAdvisor: 'Transformation Office Advisor · Change Advisor Agent',
    outputs: ['Stakeholder Engagement Plans', 'Change Readiness Reports', 'Resistance Risk Analysis', 'Organizational Change Roadmap'],
  },
  {
    id: 14,
    num: '14',
    name: 'Human Capital Intelligence',
    category: 'Operations & People',
    color: 'rose',
    difficulty: 'Intermediate',
    track: 'People & Change',
    description: 'Connect business capabilities to the people, roles, and skills required — and identify gaps that must be addressed through hiring, training, or reskilling.',
    purpose: 'Make workforce planning a strategic capability by connecting skills to capabilities, capabilities to strategy, and gaps to action.',
    subDomains: [
      { name: 'Skills Graph', description: 'Graph connecting capabilities → processes → roles → skills with current workforce possession levels and gap scoring.' },
      { name: 'Learning Engine', description: 'Personalized recommendations for training, reskilling, and upskilling paths based on capability gaps and transformation requirements.' },
      { name: 'Workforce Planning', description: 'Current workforce inventory, future requirements from TOM, gap analysis, hiring plan, reskilling investment, and transition timeline.' },
    ],
    frameworks: ['SFIA (Skills Framework for the Information Age)', 'HR Capability Models', 'Workforce Planning Standards'],
    tools: ['Workday', 'SAP SuccessFactors', 'LinkedIn Talent Insights', 'EWP Skills Graph (Neo4j)'],
    aiAdvisor: 'Transformation Office Advisor',
    outputs: ['Skills Gap Analysis', 'Workforce Transformation Plan', 'Hiring Strategy', 'Reskilling Investment Plan', 'Learning Recommendations'],
  },
  {
    id: 15,
    num: '15',
    name: 'Industry Intelligence',
    category: 'Intelligence',
    color: 'yellow',
    difficulty: 'Intermediate',
    track: 'Intelligence & Knowledge',
    description: 'Maintain living intelligence on industry players, transformation patterns, and sector benchmarks — continuously updated, not static case studies.',
    purpose: 'Ground every strategy recommendation in real-world industry context so the platform generates industry-aware advice, not generic guidance.',
    subDomains: [
      { name: 'Retail Intelligence', description: 'Omnichannel evolution, AI adoption (personalization, forecasting, checkout), supply chain transformation, and competitor tracking (Amazon, Walmart, Target, Costco).' },
      { name: 'Banking Intelligence', description: 'Digital banking disruption, AI in risk/fraud, RegTech adoption, core banking modernization, and open banking ecosystem evolution. Tracking JPMorgan, Capital One, Goldman Sachs.' },
      { name: 'Cross-Industry Patterns', description: 'Universal transformation patterns for cloud migration, AI adoption maturity, operating model transformation, data modernization, and digital product evolution.' },
    ],
    frameworks: ['Industry Analysis', 'Competitive Benchmarking', 'Pattern Recognition', 'Trend Analysis'],
    tools: ['Gartner Research', 'Forrester', 'IDC', 'Bloomberg', 'News Intelligence APIs', 'arXiv'],
    aiAdvisor: 'Chief Strategy Officer Agent',
    outputs: ['Industry Trend Reports', 'Competitor Strategy Analysis', 'Benchmark Comparisons', 'Transformation Pattern Library'],
  },
  {
    id: 16,
    num: '16',
    name: 'Scenario Planning & Simulation',
    category: 'Advanced Capabilities',
    color: 'slate',
    difficulty: 'Advanced',
    track: 'Advanced Intelligence',
    description: 'Model multiple future scenarios and simulate their enterprise-wide impact before committing to costly decisions.',
    purpose: 'Give executives the ability to stress-test strategies and investments against multiple futures — moving from gut feel to evidence-based commitment.',
    subDomains: [
      { name: 'Financial Scenarios', description: 'Revenue growth/decline, cost inflation, investment constraint, and macro impact scenarios modeled with Monte Carlo, NPV, and sensitivity analysis.' },
      { name: 'Technology Scenarios', description: 'Cloud migration paths, ERP replacement options, AI adoption curves, and vendor failure impact modeled via Enterprise Digital Twin.' },
      { name: 'Operational Scenarios', description: 'Operating model redesign, capability investment portfolios, workforce automation impact, and outsourcing vs. insourcing trade-offs.' },
    ],
    frameworks: ['Scenario Planning', 'Monte Carlo Simulation', 'Sensitivity Analysis', 'System Dynamics', 'War Gaming'],
    tools: ['Python (scipy, pandas, numpy)', 'R', 'Crystal Ball', 'Vensim', 'EWP Digital Twin'],
    aiAdvisor: 'Executive Board Advisor · CFO Advisor',
    outputs: ['Scenario Comparison Reports', 'Sensitivity Analysis', 'Executive Decision Packages', 'Strategic Contingency Plans'],
  },
  {
    id: 17,
    num: '17',
    name: 'Autonomous Transformation Office',
    category: 'Advanced Capabilities',
    color: 'zinc',
    difficulty: 'Advanced',
    track: 'Advanced Intelligence',
    description: 'Move from AI-assisted recommendations to AI-driven execution — automatically generating roadmaps, artifacts, and governance reviews.',
    purpose: 'Replace the manual overhead of transformation offices with AI-driven automation that handles routine execution while humans focus on judgment.',
    subDomains: [
      { name: 'Roadmap Automation', description: 'Auto-generate transformation roadmaps with dependency sequencing, critical path analysis, resource constraints, and Jira Epic/Story population.' },
      { name: 'Artifact Generation', description: 'Automatically produce solution architecture documents, ADRs, architecture diagrams, business cases, and design review packages.' },
      { name: 'Governance Automation', description: 'Automate ARB pre-screening, compliance gap detection, risk scoring, benefits reporting, and portfolio health monitoring.' },
    ],
    frameworks: ['Agentic AI Patterns', 'Autonomous Agent Architecture', 'Human-in-the-Loop Design'],
    tools: ['LangGraph', 'CrewAI', 'Jira API', 'GitHub Actions', 'Confluence API', 'MCP'],
    aiAdvisor: 'Transformation Office Advisor',
    outputs: ['Auto-Generated Roadmaps', 'AI-Produced Architecture Artifacts', 'Automated Governance Reviews', 'Continuous Monitoring Dashboards'],
  },
  {
    id: 18,
    num: '18',
    name: 'Enterprise Wisdom Engine',
    category: 'Advanced Capabilities',
    color: 'gradient',
    difficulty: 'Advanced',
    track: 'Advanced Intelligence',
    description: 'The synthesis layer — combining memory, knowledge, reasoning, simulation, and learning into organizational wisdom that continuously improves.',
    purpose: 'Evolve the platform from a knowledge system to a true wisdom system that can answer "What should we do next?" with enterprise-specific evidence.',
    subDomains: [
      { name: 'Reasoning Engine', description: 'Multi-step context-aware reasoning (deductive, inductive, abductive, analogical) over the enterprise knowledge graph using LangGraph + GraphRAG.' },
      { name: 'Simulation Engine', description: 'Enterprise-wide simulations modeling cascading effects of strategic decisions across capabilities, processes, technology, financials, and workforce.' },
      { name: 'Wisdom Synthesis', description: 'Synthesize patterns from enterprise memory, industry intelligence, reasoning, and simulation into distilled organizational wisdom with continuous learning loops.' },
    ],
    frameworks: ['Knowledge → Intelligence → Wisdom Model', 'Continuous Learning Systems', 'Cognitive Architecture Patterns'],
    tools: ['LangGraph', 'GraphRAG', 'Neo4j', 'Claude / GPT / Gemini', 'Vector Databases', 'Semantic Kernel'],
    aiAdvisor: 'All AI Advisors (Orchestrated)',
    outputs: ['Organizational Wisdom Repository', 'Executive Strategic Briefings', 'Transformation Pattern Intelligence', 'Continuous Intelligence Updates'],
  },
]

export const stats = {
  domains: 18,
  subDomains: 89,
  frameworks: 60,
  tools: 45,
  aiAdvisors: 8,
  tracks: 7,
}
